//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gui.Presentation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Splash {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Splash() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gui.Presentation.Resources.Splash", typeof(Splash).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DevelopementPlay.
        /// </summary>
        internal static string ButtonDevelopement {
            get {
                return ResourceManager.GetString("ButtonDevelopement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wczytaj mapę.
        /// </summary>
        internal static string ButtonLoadMap {
            get {
                return ResourceManager.GetString("ButtonLoadMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytor map.
        /// </summary>
        internal static string ButtonMapEditor {
            get {
                return ResourceManager.GetString("ButtonMapEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wielu graczy.
        /// </summary>
        internal static string ButtonMultiPlayer {
            get {
                return ResourceManager.GetString("ButtonMultiPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowa mapa.
        /// </summary>
        internal static string ButtonNewMap {
            get {
                return ResourceManager.GetString("ButtonNewMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graj.
        /// </summary>
        internal static string ButtonPlay {
            get {
                return ResourceManager.GetString("ButtonPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorzy.
        /// </summary>
        internal static string ButtonsAbout {
            get {
                return ResourceManager.GetString("ButtonsAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opcje.
        /// </summary>
        internal static string ButtonSettings {
            get {
                return ResourceManager.GetString("ButtonSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyjście.
        /// </summary>
        internal static string ButtonsExit {
            get {
                return ResourceManager.GetString("ButtonsExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeden gracz.
        /// </summary>
        internal static string ButtonSinglePlayer {
            get {
                return ResourceManager.GetString("ButtonSinglePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kamil Markuszewski 
        ///171016.
        /// </summary>
        internal static string LabelAbout {
            get {
                return ResourceManager.GetString("LabelAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorzy.
        /// </summary>
        internal static string MenuTitleAbout {
            get {
                return ResourceManager.GetString("MenuTitleAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string MenuTitleMain {
            get {
                return ResourceManager.GetString("MenuTitleMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytor map.
        /// </summary>
        internal static string MenuTitleMapEditor {
            get {
                return ResourceManager.GetString("MenuTitleMapEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zagraj.
        /// </summary>
        internal static string MenuTitlePlay {
            get {
                return ResourceManager.GetString("MenuTitlePlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustawienia.
        /// </summary>
        internal static string MenuTitleSettings {
            get {
                return ResourceManager.GetString("MenuTitleSettings", resourceCulture);
            }
        }
    }
}
